# Build Docker image for this app using Azure Pipelines
# http://docs.microsoft.com/azure/devops/pipelines/languages/docker?view=vsts
pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    dotnet build ./JuszczakTech.Server/JuszczakTech.Server.csproj --configuration Release
    dotnet publish ./JuszczakTech.Server/JuszczakTech.Server.csproj --configuration Release --output ../out -r linux-arm
    docker build -f Dockerfile -t juszczak.tech .

